name: Build PyQt Application

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'  # Укажите нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pyinstaller

      - name: Build the application
        run: |
          pyinstaller --onefile my_app/main.py  # Замените на имя вашего скрипта
          
      - name: Check if .exe was created
        run: |
          if [ -f dist/main.exe ]; then
            echo "Build successful: .exe file created."
          else
            echo "Build failed: .exe file not created."
            exit 1
          fi
